### PR TITLE
add an optional Transcode option

### PR DESCRIPTION
**Pull request by xdrie**
when `transcode` is enabled in configuration, it will request Jellyfin to stream in `.ogg`.

### CODE REVIEW

**Comment by xdrie** [comment]
yes, i noticed that this breaks seeking as well. is there anything we can do about it?

**Comment by xdrie** [comment]
also, I believe we can support the max bitrate using `AudioBitrate` (see http://swagger.emby.media/?staticview=true#/AudioService/getAudioByIdByContainerfor the closest thing to docs i could find)

**Comment by mcarlton00** [comment]
I'm sure there's a better solution, but off the top of my head the somewhat hacky method would be on seeking to kill the existing playback session and start a new one at the new time.  But given that there's a fairly significant delay on transcode start, I don't think that's the best method forward.

The bitrate would be a more elegant solution, but also a bit more involved.  As of right now the playback class doesn't receive the full payload, only the mopidy uri.  And I don't think there's a good way to pass it in there.  We _could_ do an api request to get bitrate there and determine transcode, but that could also be a slow.  We could call `self.backend.remote.get_item(id)` and pull the bitrate there.  Or it could check container type and transcode only user submitted formats.  Not sure what the better option there would be.  It would need some testing.

**Comment by xdrie** [comment]
with Ogg at least, I tried downloading the transcoded files and they are encoded as variable bitrate. with that it might not be viable to support using the bitrate to seek.

it might be better to simply start a new playback session; though as you said this would introduce some latency and overhead on the server-side.

**Comment by mcarlton00** [comment]
So far it looks like we can't even capture the seek event while transcoding is active.  When seeking during normal playback, we can catch a `position_changed` or `seeked` event from mopidy.  Example:
```
INFO     2020-04-04 12:37:30,999 [2155809:EventMonitorFrontend-9] mopidy_jellyfin.frontend
  Event: position_changed
INFO     2020-04-04 12:37:30,999 [2155809:EventMonitorFrontend-9] mopidy_jellyfin.frontend
  kwargs: {'position': 0}
INFO     2020-04-04 12:37:30,999 [2155809:EventMonitorFrontend-9] mopidy_jellyfin.frontend
  Event: seeked
INFO     2020-04-04 12:37:30,999 [2155809:EventMonitorFrontend-9] mopidy_jellyfin.frontend
  kwargs: {'time_position': 31000}
```

However when transcoding is active and you try to seek, it doesn't register that anything has happened.  I dropped a couple extra log statements in to investigate.  The code that handles that is found here:
https://github.com/jellyfin/mopidy-jellyfin/blob/afdc4d16ad3c1c25cd102e18940e35ee2d6bc416/mopidy_jellyfin/frontend.py#L40-L49

**Comment by mcarlton00** [comment]
More details:

Looks like this is the exact situation that the previous dev ran into when writing it initially: https://emby.media/community/index.php?/topic/42501-seek-in-a-stream-from-the-api/

**Comment by mcarlton00** [comment]
Superseded by #65

**Pull request closed without merging**
