### PR TITLE
Correcting : unsupported operand type(s) for /: 'str' and 'unicode'

### PR DESCRIPTION
**Pull request by xt0ph**
I have this error when i try the last version, this solve my error.

### CODE REVIEW

**Comment by xt0ph** [comment]
it may be a pb under other OS, it would be safer to use 'os.path.join' what do you think?

**Comment by mcarlton00** [comment]
Strange that it works for me without throwing errors.  Maybe a distro specific python thing.

Yeah, `os.path.join(cache_dir, 'token') is a much better solution.

**Comment by kingosticks** [comment]
That error message can only have occurred under Python 2 (where `str` *is not* unicode). The original code at https://github.com/jellyfin/mopidy-jellyfin/pull/38/commits/7625165d0489a062cf38d6e59c302cd8c0c99af3 works on Python 3. `os.path` is inferior to `Pathlib`, particularly when it comes to non-UTF8 paths.

**Comment by mcarlton00** [comment]
Thanks for the explanation, that makes sense why I never saw the error.  I haven't purposely disabled Python 2 support, but I've stopped doing any checks against it.  This serves as a reminder that I really need to get the tests working

**Pull request merged**
